packageExtensions:
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-4.0.0.cjs
